name = "thyrosimIM"
uuid = "d1e97bd1-1d48-47cb-b7b8-cf521c928b80"
authors = ["Aidan Boyne <aidanboyne@g.ucla.edu>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
